// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOpti
///   ons.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU-Mtl8mrnirBfcpAN5ToXXnKJTwdW3NI',
    appId: '1:835032391343:web:0d22c41f5e88f699e3be5a',
    messagingSenderId: '835032391343',
    projectId: 'harmonyrewards',
    authDomain: 'harmonyrewards.firebaseapp.com',
    storageBucket: 'harmonyrewards.appspot.com',
    measurementId: 'G-PK12NCRQWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0PoXJRmvnj0BaNtPF8ZBpenfAfIvJyo',
    appId: '1:835032391343:android:61798b68aa4d74d5e3be5a',
    messagingSenderId: '835032391343',
    projectId: 'harmonyrewards',
    storageBucket: 'harmonyrewards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPdVUZ4u1lZkwL0kmufF0az-HPm9CvDpo',
    appId: '1:835032391343:ios:27aac3416933ef0ce3be5a',
    messagingSenderId: '835032391343',
    projectId: 'harmonyrewards',
    storageBucket: 'harmonyrewards.appspot.com',
    iosBundleId: 'com.mycompany.defi',
  );

}